### ISSUE TITLE
Target audience missing

### ISSUE THREAD

**Issue by emilgras** [Thug-Lyfe/UFO_Blog#1]
Describing in the beginning who the target audience is would be great. Obviously it is for developers. But is it relevant for all types, beginners and advanced?

**Comment by Thug-Lyfe** [comment]
This blog was meant for students or people with minor understanding of ssh, droplets etc.
Though we didn’t want prevent people who had prior knowledge of some of the things to skip ahead and go directly to installing Jenkins
In hindsight we should have focused on the target audience early in the blog, so the reader knows at which level this guide is meant for.
Bloggen var mest for studerende eller folk med mindre med mindre forståelse inden for ssh, droplets osv.

**Comment by Thug-Lyfe** [comment]
We made the blog more in tune with a guide and included students in the abstract, to more clearly signal that it is not for advanced users.
