### ISSUE TITLE
Idea: Historical overview

### ISSUE THREAD

**Issue by andersbjergfelt** [Thug-Lyfe/UFO_Blog#10]
**Historical overview**
This is just an idea to add to your blog. You could actually dedicate a small section to compare how integration was done previously in companies and how CI has tackled that today. Providing a historical background helps underline WHY CI and Jenkins is a smart thing to do, and in the end helps to convince the reader that he/she should use it.

**Comment by ChristianLind** [comment]
We might do a section about the historical background and it could be an interesting read, we are taking it up to consideration, but we will most likely put our work into alternatives and better theory, specifically between CI, delivery and deployment.

**Comment by Thug-Lyfe** [comment]
We have not gotten much into the historical background, but we have written a more in depth reasoning for why these practices are good things to implement.
