### ISSUE TITLE
Good structure

### ISSUE THREAD

**Issue by andersbjergfelt** [Thug-Lyfe/UFO_Blog#12]
You have clearly thought about the structure of your blog. You start with a short headliner to catch the readers attention. Followed by a short introduction to CI and Jenkins. And then you continue with a very useful pros and cons of using CI, and then present the reader with a "how to get started using Jenkins" guide. Lastly, you summarize most of the things above it. Good structure.

**Comment by Thug-Lyfe** [comment]
Thank you for your feedback! We will try and keep the structure for the next iteration of the blog, even when changing several things throughout the blog.
