### ISSUE TITLE
Confusion about Integration vs. Deployment

### ISSUE THREAD

**Issue by emilgras** [Thug-Lyfe/UFO_Blog#2]
Confusion about the introduction and ending. The headline uses CI, but your first line reads "Every developer has been in the situation where they have to deploy a webapp". You are talking about deployment and integration as they are equal. I know that Jenkins can be used for CI & CD, but you have chosen to focus on CI.

The ending, again, talks about deployment. Maybe you should explain the difference between integration and deployment using Jenkins. They are to different operations, but you can definitely use Jenkins for both.

**Comment by Thug-Lyfe** [comment]
We can see that it might be confusing. You are certainly right that we have written it as if they are the same, when they have different purposes. We will write a section about continuous delivery and continuous deployment for revised version. We will also try and separate the subjects to better clarify them.

**Comment by Thug-Lyfe** [comment]
We have heard your criticism and have taken it to heart, we have written more in depth, with separate sections, about Continuous Integration, Delivery and Deployment. We hope it has become more clear now.
