### ISSUE TITLE
Theoretical Explanations

### ISSUE THREAD

**Issue by emilgras** [Thug-Lyfe/UFO_Blog#3]
I believe you are missing an important aspect as to WHY we use CI and Jenkins. The fundamental reason WHY is missing.

WHY does CI help us integrate more often/continuously? Why couldn't we just instruct our developers to merge more often without using Jenkins?. Wouldn't that solve the same issue? What exactly is the risk when we merge to a shared repo? 

Technical depth is missing? Yes, you say that developers are often struggling with merge conflicts. What CI does, is that it makes sure that AFTER a merge your system as a whole still works and builds and functions as normal. It brings confidence to the developer that what he or she developed works AND integrates with the system. It provides a safety net. AND THAT is the reason why you can continuously integrate with high confidence.

**Comment by ChristianLind** [comment]
You got a point considering getting more in depth and that it got a little messy from time to time.
As mentioned in issue #2, our intention would be to make a deployment and a delivery section, which could separate the subjects, and explain what each of them are.
We want to work some more on the part about explaining CI and why you want to use it for the next iteration of the blog.

**Comment by Thug-Lyfe** [comment]
We have added more reasoning about what using Continuous integration, Delivery and Deployment can lead to. It felt a bit forced writing specifically this is why, instead of this is what it is good for.
