### ISSUE TITLE
Relevant Links

### ISSUE THREAD

**Issue by emilgras** [Thug-Lyfe/UFO_Blog#5]
Very relevant and informative links. 👍

**Comment by ChristianLind** [comment]
Thank you for the feedback! From our perspective we could have used some more links and references, which is our intention for the next iteration, along the lines of:
https://www.digitalocean.com/community/tutorials/ci-cd-tools-comparison-jenkins-gitlab-ci-buildbot-drone-and-concourse 
https://stackify.com/top-continuous-integration-tools/ 
https://wiki.jenkins.io/pages/viewpage.action?pageId=53608972 
https://www.infoworld.com/article/3046038/application-development/why-jenkins-is-becoming-the-engine-of-devops.html

**Comment by Thug-Lyfe** [comment]
We have added a lot more references and made them more accessible. We hope they are still at least up to par or better.
