### ISSUE TITLE
Assumptions

### ISSUE THREAD

**Issue by andersbjergfelt** [Thug-Lyfe/UFO_Blog#6]
**Assumptions**
"Why don't we see more Jenkins?". That is one of your questions. Have you made any research to check if Jenkins is not popular and not used in industry? You make assumptions that Jenkins is not popular. You would be seen as more trustworthy with data proving that assumption.  Maybe it would make sense if you talk about how Jenkins is harder to get started with because of more advanced configurations than other CI services like Travis CI.

**Comment by ChristianLind** [comment]
You are right, we were pressed for time and would have been better served with doing some more data mining, we will be sure to get some for the next iteration of the blog.
something in the lines of:
https://wiki.jenkins.io/pages/viewpage.action?pageId=58001258 
https://stackshare.io/gitlab-ci 
https://stackshare.io/stackups/buildbot-vs-jenkins 
https://stackshare.io/drone-io

**Comment by Thug-Lyfe** [comment]
We have added more sources and done a more thorough investigation of who uses Jenkins. We have not gone much into Travis CI, though we have made some investigation into GitLAb and TeamCity.
