### ISSUE TITLE
Grades

### ISSUE THREAD

**Issue by emilgras** [Thug-Lyfe/UFO_Blog#7]
This is how we graded your blog based on these criteria: https://datsoftlyngby.github.io/soft2017fall/UFO/technicalreportrubric.pdf

Overview --> 7

Reliable Data
from Credible
Sources --> 3

Design
Constraints
and
Assumptions --> 3-4

Theoretical
Explanations -->  6

Design
Criteria,
Sample
Calculations
and
Simulations --> 7

Previous
Work/ Future
Work --> 5-6?

**Comment by Thug-Lyfe** [comment]
Thank you for the time and effort you put into our blog.
