### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by andersbjergfelt** [Thug-Lyfe/UFO_Blog#8]
**No alternatives**
You lack alternatives to Jenkins. It would be nice to know what other software/services you could use, and how Jenkins compares to other services? Is it better / worse / easier / harder / more expensive etc.

**Comment by ChristianLind** [comment]
In hindsight we should have had added such a part to the blog. After listing the good and bad things about using Jenkins, naming other alternatives would have been a very good idea.
such as: Gitlab-ci, Buildbot and Drone.io which will make a section about in the next iteration. something in the lines of:
https://www.blazemeter.com/blog/jenkins-vs-other-open-source-continuous-integration-servers 
https://www.digitalocean.com/community/tutorials/ci-cd-tools-comparison-jenkins-gitlab-ci-buildbot-drone-and-concourse

**Comment by Thug-Lyfe** [comment]
We have added segments about two other CI/CD alternatives.
