### ISSUE TITLE
Wrong fact

### ISSUE THREAD

**Issue by andersbjergfelt** [Thug-Lyfe/UFO_Blog#9]
**Wrong fact**
In "Pros for CI over Manual integration" you state that using CI results in no merge conflicts. This is not true. Jenkins does not eliminate merge conflicts. You can still have them. And if you do you cannot merge to master branch. Merge conflicts still need to be manually resolved if they appear. Jenkins help you make sure that WHEN you merge, your system is still working as a whole.

**Comment by Thug-Lyfe** [comment]
you are right that there can be merge conflicts. it was an embellishment on our side. even if there is merge conflicts jenkins does not usually have much to do with it as it gets taken care of within git between branches and master.

**Comment by Thug-Lyfe** [comment]
We have removed the wrong fact and elaborated on other subjects regarding Jenkins and other CI/CD tools.
